"""add employee role

Revision ID: 21858b3c68f3
Revises: 26b4d61f90f8
Create Date: 2023-09-20 00:49:01.848223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21858b3c68f3'
down_revision: Union[str, None] = '26b4d61f90f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('assets', sa.Column('type', sa.String(length=100), nullable=False))
    op.drop_constraint('assets_type_id_fkey', 'assets', type_='foreignkey')
    op.drop_constraint('assets_cost_center_id_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'cost_center_id')
    op.drop_column('assets', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('cost_center_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('assets_cost_center_id_fkey', 'assets', 'cost_center', ['cost_center_id'], ['id'])
    op.create_foreign_key('assets_type_id_fkey', 'assets', 'asset_types', ['type_id'], ['id'])
    op.drop_column('assets', 'type')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('roles')
    # ### end Alembic commands ###
