"""adjust assets

Revision ID: 8e9888d1595d
Revises: cf4c58700ffd
Create Date: 2023-09-19 23:21:26.473993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e9888d1595d'
down_revision: Union[str, None] = 'cf4c58700ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('assets', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('assets_status_id_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('assets_status_id_fkey', 'assets', 'asset_status', ['status_id'], ['id'])
    op.drop_column('assets', 'active')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
