"""other models

Revision ID: 50cd99387053
Revises: 454f8bf25e41
Create Date: 2023-09-02 21:54:55.296847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50cd99387053'
down_revision: Union[str, None] = '454f8bf25e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_clothing_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('taxpayer_identification', sa.String(), nullable=False),
    sa.Column('nacional_identification', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cell_phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cost_center_number', sa.String(), nullable=True),
    sa.Column('cost_center_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('checksum', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('taxpayer_identification')
    )
    op.create_table('syncs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('count_new_values', sa.Integer(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('clothing_size_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('assurance_date', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('discard_reason', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('operational_system', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ms_office', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('accessories', sa.String(), nullable=True),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_size_id'], ['asset_clothing_sizes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['asset_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['asset_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('assets')
    op.drop_table('syncs')
    op.drop_table('employees')
    op.drop_table('asset_types')
    op.drop_table('asset_status')
    op.drop_table('asset_clothing_sizes')
    # ### end Alembic commands ###
