"""fix user model

Revision ID: b22520e6b6fa
Revises: 511b9011ddf9
Create Date: 2023-10-24 22:44:50.991794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22520e6b6fa'
down_revision: Union[str, None] = '511b9011ddf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_taxpayer_identification_key', 'user', type_='unique')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'taxpayer_identification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('taxpayer_identification', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_taxpayer_identification_key', 'user', ['taxpayer_identification'])
    # ### end Alembic commands ###
