"""finished type template change

Revision ID: 89abd7f1dabe
Revises: ba6ccfc7e7a3
Create Date: 2023-10-12 21:59:05.670275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89abd7f1dabe'
down_revision: Union[str, None] = 'ba6ccfc7e7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type', sa.Column('doc_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_type', 'document_template', ['doc_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_type', type_='foreignkey')
    op.drop_column('document_type', 'doc_template_id')
    # ### end Alembic commands ###
