"""initial

Revision ID: 314b55307392
Revises: 
Create Date: 2023-09-16 23:44:15.891532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314b55307392'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_clothing_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_center',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('taxpayer_identification', sa.String(), nullable=False),
    sa.Column('nacional_identification', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cell_phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cost_center_number', sa.String(), nullable=True),
    sa.Column('cost_center_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('taxpayer_identification')
    )
    op.create_table('gender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrimonial_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nationality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('clothing_size_id', sa.Integer(), nullable=False),
    sa.Column('register_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('assurance_date', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('discard_reason', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('operational_system', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ms_office', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('accessories', sa.String(), nullable=True),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_size_id'], ['asset_clothing_size.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['asset_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['asset_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('gpli_number', sa.String(length=50), nullable=True),
    sa.Column('supplier_service_order', sa.String(length=50), nullable=True),
    sa.Column('supplier_number', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['maintenance_action.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['maintenance_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role'], ['role.id'], )
    )
    op.create_table('upgrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('glpi_number', sa.String(length=50), nullable=True),
    sa.Column('detailing', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['maintenance_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('taxpayer_identification', sa.String(length=14), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('taxpayer_identification'),
    sa.UniqueConstraint('username')
    )
    op.create_table('witness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('signed', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_template_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['doc_template_id'], ['document_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('glpi_number', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_center.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['workload_id'], ['workload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lending_id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lending_id'], ['lending.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['verification_type.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('witnesses',
    sa.Column('lending_id', sa.Integer(), nullable=True),
    sa.Column('witness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lending_id'], ['lending.id'], ),
    sa.ForeignKeyConstraint(['witness_id'], ['witness.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('witnesses')
    op.drop_table('verification_answer')
    op.drop_table('lending')
    op.drop_table('token')
    op.drop_table('maintenance_attachment')
    op.drop_table('document')
    op.drop_table('witness')
    op.drop_table('user')
    op.drop_table('upgrade')
    op.drop_table('role_permissions')
    op.drop_table('maintenance')
    op.drop_table('document_template')
    op.drop_table('asset')
    op.drop_table('workload')
    op.drop_table('verification_type')
    op.drop_table('verification')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('nationality')
    op.drop_table('matrimonial_status')
    op.drop_table('maintenance_status')
    op.drop_table('maintenance_action')
    op.drop_table('gender')
    op.drop_table('employees')
    op.drop_table('document_type')
    op.drop_table('cost_center')
    op.drop_table('asset_type')
    op.drop_table('asset_status')
    op.drop_table('asset_clothing_size')
    # ### end Alembic commands ###
