"""adjust employee roles

Revision ID: 716bae0226f1
Revises: 71ec8800c66c
Create Date: 2023-09-22 22:45:01.813265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716bae0226f1'
down_revision: Union[str, None] = '71ec8800c66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_role_id_fkey', 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_role_id_fkey', 'employees', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
