"""change role permissions

Revision ID: 99476a0f304f
Revises: 314b55307392
Create Date: 2023-09-17 16:00:31.305324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99476a0f304f'
down_revision: Union[str, None] = '314b55307392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('role_permissions', sa.Column('permission_id', sa.Integer(), nullable=True))
    op.drop_constraint('role_permissions_permission_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_role_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permission', ['permission_id'], ['id'])
    op.drop_column('role_permissions', 'permission')
    op.drop_column('role_permissions', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('role_permissions', sa.Column('permission', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_fkey', 'role_permissions', 'role', ['role'], ['id'])
    op.create_foreign_key('role_permissions_permission_fkey', 'role_permissions', 'permission', ['permission'], ['id'])
    op.drop_column('role_permissions', 'permission_id')
    op.drop_column('role_permissions', 'role_id')
    # ### end Alembic commands ###
