"""add log

Revision ID: 1f0ec25360d3
Revises: c0f0ee986112
Create Date: 2023-10-06 17:36:21.048021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0ec25360d3'
down_revision: Union[str, None] = 'c0f0ee986112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('by_agile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'by_agile')
    # ### end Alembic commands ###
