"""permission add description

Revision ID: 49e8805fa9f4
Revises: 99476a0f304f
Create Date: 2023-09-22 00:58:43.653038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e8805fa9f4'
down_revision: Union[str, None] = '99476a0f304f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('action', sa.String(), nullable=True))
    op.add_column('permission', sa.Column('description', sa.String(length=150), nullable=True))
    op.drop_column('permission', 'method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('permission', 'description')
    op.drop_column('permission', 'action')
    # ### end Alembic commands ###
