"""adjust permissions

Revision ID: 5c6b4ba5803c
Revises: 49e8805fa9f4
Create Date: 2023-09-22 01:08:33.192145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6b4ba5803c'
down_revision: Union[str, None] = '49e8805fa9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('permission', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
