"""change doc relationship

Revision ID: 4ecad0903d4b
Revises: 054b07574d80
Create Date: 2023-10-12 21:53:10.643437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecad0903d4b'
down_revision: Union[str, None] = '054b07574d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type', sa.Column('acronym', sa.String(), nullable=True))
    op.drop_constraint('document_doc_template_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'doc_template_id')
    op.drop_column('document', 'number')
    op.drop_column('document_template', 'content')
    op.add_column('lending', sa.Column('number', sa.String(length=30), nullable=False))
    op.alter_column('lending', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lending', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lending', 'number')
    op.add_column('document_template', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('doc_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_doc_template_id_fkey', 'document', 'document_template', ['doc_template_id'], ['id'])
    op.drop_column('asset_type', 'acronym')
    # ### end Alembic commands ###
