"""adjust employee role to row back

Revision ID: 0d8c6949ef95
Revises: 172d7651bd4a
Create Date: 2023-09-22 22:59:14.232549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8c6949ef95'
down_revision: Union[str, None] = '172d7651bd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('employees_post_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employee_roles', ['role_id'], ['id'])
    op.drop_column('employees', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_post_id_fkey', 'employees', 'employee_roles', ['post_id'], ['id'])
    op.drop_column('employees', 'role_id')
    # ### end Alembic commands ###
