"""change type template relationship

Revision ID: ba6ccfc7e7a3
Revises: 4ecad0903d4b
Create Date: 2023-10-12 21:57:40.173055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6ccfc7e7a3'
down_revision: Union[str, None] = '4ecad0903d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'document_type', ['doc_type_id'], ['id'])
    op.drop_constraint('document_template_type_id_fkey', 'document_template', type_='foreignkey')
    op.drop_column('document_template', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_template', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_template_type_id_fkey', 'document_template', 'document_type', ['type_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'doc_type_id')
    # ### end Alembic commands ###
