"""adjust person model

Revision ID: 71ec8800c66c
Revises: 5c6b4ba5803c
Create Date: 2023-09-22 21:11:34.442648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ec8800c66c'
down_revision: Union[str, None] = '5c6b4ba5803c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nationality')
    op.drop_table('gender')
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('nationality_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('marital_status_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('gender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'genders', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'nationalities', ['nationality_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'matrimonial_status', ['marital_status_id'], ['id'])
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'cost_center_name')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'cost_center_number')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('cost_center_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('cost_center_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'gender_id')
    op.drop_column('employees', 'marital_status_id')
    op.drop_column('employees', 'nationality_id')
    op.drop_column('employees', 'role_id')
    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gender_pkey')
    )
    op.create_table('nationality',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nationality_pkey')
    )
    op.drop_table('roles')
    op.drop_table('nationalities')
    op.drop_table('genders')
    # ### end Alembic commands ###
