"""verification

Revision ID: 511b9011ddf9
Revises: ad0767bbdd00
Create Date: 2023-10-22 04:54:00.240323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511b9011ddf9'
down_revision: Union[str, None] = 'ad0767bbdd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification', sa.Column('asset_type_id', sa.Integer(), nullable=False))
    op.add_column('verification', sa.Column('step', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'verification', 'asset_type', ['asset_type_id'], ['id'])
    op.add_column('verification_answer', sa.Column('observations', sa.String(length=255), nullable=True))
    op.alter_column('verification_answer', 'answer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('verification_answer', 'step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_answer', sa.Column('step', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('verification_answer', 'answer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('verification_answer', 'observations')
    op.drop_constraint(None, 'verification', type_='foreignkey')
    op.drop_column('verification', 'step')
    op.drop_column('verification', 'asset_type_id')
    # ### end Alembic commands ###
