"""fix document type name length

Revision ID: 054b07574d80
Revises: 1f0ec25360d3
Create Date: 2023-10-06 20:15:29.113318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054b07574d80'
down_revision: Union[str, None] = '1f0ec25360d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_center', sa.Column('group_name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_center', 'group_name')
    # ### end Alembic commands ###
