"""remove relationship doc template

Revision ID: 2472201efff7
Revises: 61023f746026
Create Date: 2023-10-21 16:42:17.332973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2472201efff7'
down_revision: Union[str, None] = '61023f746026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_type_doc_template_id_fkey', 'document_type', type_='foreignkey')
    op.drop_column('document_type', 'doc_template_id')
    op.add_column('employees', sa.Column('employer_number', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('employer_address', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('employer_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'employee_id')
    op.drop_column('employees', 'employer_name')
    op.drop_column('employees', 'employer_address')
    op.drop_column('employees', 'employer_number')
    op.add_column('document_type', sa.Column('doc_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_type_doc_template_id_fkey', 'document_type', 'document_template', ['doc_template_id'], ['id'])
    # ### end Alembic commands ###
