"""add employee pj

Revision ID: 3547233a1357
Revises: 0d8c6949ef95
Create Date: 2023-09-22 23:10:03.919844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3547233a1357'
down_revision: Union[str, None] = '0d8c6949ef95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('legal_person', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'legal_person')
    # ### end Alembic commands ###
