# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-ast # Validate python
-  repo: https://github.com/hadialqattan/pycln
   rev: v1.0.3
   hooks:
      - id: pycln # Remove unused imports
        args: ["--all"]
-  repo: https://github.com/pycqa/isort
   rev: 5.10.1
   hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-  repo: https://github.com/psf/black
   rev: 21.10b0
   hooks:
      - id: black # Python code auto formatter
        additional_dependencies: ['click==8.0.4']
        exclude: __init__.py
-  repo: local
   hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test
        # args: ["--exclude-tag"]
        always_run: true
        pass_filenames: false
        language: system
-  repo: local
   hooks:
      - id: restricted-filenames
        name: Check commits for unexpected file extensions
        entry: These file extensions are unusual and should be checked
        language: fail
        files: '.*\.(xlsx|doc|tif|png|npz|jpg|jpeg|gif)'
      - id: restricted-file-types
        name: Check commits for unexpected file types
        entry: These file types are unusual and should be checked
        language: fail
        types: ['binary']
        exclude_types: ['image']
