apiVersion: v1
kind: Namespace
metadata:
  name: solutis
  labels:
    name: solutis
---
apiVersion: v1
kind: Secret
metadata:
  name: env-agile
  namespace: solutis
data:
  SECRET_KEY: PSV1OHQjJClycXR1XiViJSklcyR4bz11IXB3dik0NF9kKCVed2MpNTF3YSEpb29nZCo=
  TIMEZONE: QW1lcmljYS9CYWhpYQ==
  # Banco Solutis Agile
  MYSQL_SERVER: MTcyLjIzLjk2LjE=
  # MYSQL_SERVER: host.docker.internal
  MYSQL_DATABASE: YWdpbGU=
  MYSQL_USER: bG9jYWxfdXNlcg==
  MYSQL_PASSWORD: c29sdXRpczEyMw==
  PASSWORD_SUPER_USER: c2FnaWxlQGFkbWluMTIz
  DEBUG: VHJ1ZQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: agile-app
  namespace: solutis
  labels:
    app: agile-app
spec:
  containers:
    - name: agile-app
      image: pedrogls/agile:latest
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: SECRET_KEY
        - name: TIMEZONE
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: TIMEZONE
        - name: MYSQL_SERVER
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: MYSQL_SERVER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: MYSQL_PASSWORD
        - name: PASSWORD_SUPER_USER
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: PASSWORD_SUPER_USER
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: env-agile
              key: DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: agile-service
  namespace: solutis
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: agile-app
