version: "3.1"

services:
  agile:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/solutis-agile/src
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    networks:
      - agile-network
  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - agile-network

networks:
  agile-network:
    driver: bridge
