version: "3.1"

services:

  # Backend principal
  app:
    build:
      context: .
    environment:
      TZ: "America/Salvador"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
    env_file:
      - ./.env

  # Serviço de consumo do SQL SERVER
  # datasync-totvs:
  #   build:
  #     context: .
  #   # environment:
  #   #   TZ: "America/Salvador"
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - ./datasync:/datasync
  #   working_dir: /datasync
  #   command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
  #   env_file:
  #     - ./.env

  # Banco de dados que será utilizado
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql
