"""adjust asset status

Revision ID: 039fe592844b
Revises: 0cadeeb82018
Create Date: 2023-12-13 21:28:47.405977

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '039fe592844b'
down_revision: Union[str, None] = '0cadeeb82018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
