"""adjust group permissions

Revision ID: 4d6e78a1cf8a
Revises: cbcb2732703c
Create Date: 2023-12-18 21:35:00.124120

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d6e78a1cf8a'
down_revision: Union[str, None] = 'cbcb2732703c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_permissions', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('group_permissions', 'permission_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('group_permissions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_permissions', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('group_permissions', 'permission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('group_permissions', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
