"""adjust asset totvs model 5

Revision ID: 6a5b8f9719d9
Revises: 2573db876403
Create Date: 2023-12-05 22:29:15.673623

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a5b8f9719d9'
down_revision: Union[str, None] = '2573db876403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=sa.String(length=600),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
