"""adjust colmun name

Revision ID: 3fe3538f53b6
Revises: d1652bdd9971
Create Date: 2023-12-13 21:48:45.129372

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fe3538f53b6'
down_revision: Union[str, None] = 'd1652bdd9971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_totvs', sa.Column('national_identification', sa.String(length=15), nullable=False))
    op.drop_column('employees_totvs', 'nacional_identification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_totvs', sa.Column('nacional_identification', mysql.VARCHAR(length=15), nullable=False))
    op.drop_column('employees_totvs', 'national_identification')
    # ### end Alembic commands ###
