"""adjust asset totvs model 2

Revision ID: 4794f135dba5
Revises: 9eb3fcc2f88d
Create Date: 2023-12-05 22:18:20.362101

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4794f135dba5'
down_revision: Union[str, None] = '9eb3fcc2f88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets_totvs', sa.Column('unit', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets_totvs', 'unit')
    # ### end Alembic commands ###
