"""adjust asset totvs model

Revision ID: 9eb3fcc2f88d
Revises: 34fc62f52034
Create Date: 2023-12-05 22:15:19.394029

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9eb3fcc2f88d'
down_revision: Union[str, None] = '34fc62f52034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets_totvs', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets_totvs', 'quantity')
    # ### end Alembic commands ###
