"""adjust asset totvs model 3

Revision ID: e2b4b8c83ac0
Revises: 4794f135dba5
Create Date: 2023-12-05 22:22:05.387709

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2b4b8c83ac0'
down_revision: Union[str, None] = '4794f135dba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
