"""add refresh token

Revision ID: 0d0a068d78bb
Revises: a3fcb296757b
Create Date: 2023-11-26 18:23:56.626259

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d0a068d78bb'
down_revision: Union[str, None] = 'a3fcb296757b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('refresh_token', sa.String(length=255), nullable=False))
    op.add_column('token', sa.Column('refresh_expires_in', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'token', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_column('token', 'refresh_expires_in')
    op.drop_column('token', 'refresh_token')
    # ### end Alembic commands ###
