"""adjust asset clothing size

Revision ID: fe5977c54d5a
Revises: 039fe592844b
Create Date: 2023-12-13 21:30:21.781468

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe5977c54d5a'
down_revision: Union[str, None] = '039fe592844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'clothing_size_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'clothing_size_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
