"""fix asset totvs model

Revision ID: 8d84f45c3a87
Revises: 6a7ca06decc7
Create Date: 2023-12-06 21:37:22.625249

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d84f45c3a87'
down_revision: Union[str, None] = '6a7ca06decc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets_totvs', 'configuration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets_totvs', sa.Column('configuration', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
