"""add datasync models

Revision ID: 98d745b5841a
Revises: 083760c6e8d3
Create Date: 2023-12-03 13:19:41.023817

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98d745b5841a'
down_revision: Union[str, None] = '083760c6e8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_number', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('assurance_date', sa.DateTime(), nullable=True),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('discard_reason', sa.String(length=255), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('operational_system', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('imei', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ms_office', sa.Boolean(), nullable=True),
    sa.Column('line_number', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('accessories', sa.String(length=255), nullable=True),
    sa.Column('configuration', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cost_centers_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('group_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('taxpayer_identification', sa.String(length=11), nullable=False),
    sa.Column('nacional_identification', sa.String(length=15), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('cell_phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('taxpayer_identification')
    )
    op.create_table('genders_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marital_status_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nationalities_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syncs_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('count_new_values', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_table('syncs_totvs')
    op.drop_table('roles_totvs')
    op.drop_table('nationalities_totvs')
    op.drop_table('marital_status_totvs')
    op.drop_table('genders_totvs')
    op.drop_table('employees_totvs')
    op.drop_table('cost_centers_totvs')
    op.drop_table('assets_totvs')
    op.drop_table('asset_types_totvs')
    # ### end Alembic commands ###
