"""fix cost center asset totvs modal

Revision ID: 57fcee85687a
Revises: 8d84f45c3a87
Create Date: 2023-12-07 18:20:43.290447

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57fcee85687a'
down_revision: Union[str, None] = '8d84f45c3a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets_totvs', sa.Column('cost_center', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets_totvs', 'cost_center')
    # ### end Alembic commands ###
