"""nullable code employee

Revision ID: d9875e7cf2e4
Revises: 63206f3144fc
Create Date: 2023-12-22 22:58:50.027398

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9875e7cf2e4'
down_revision: Union[str, None] = '63206f3144fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_totvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('employees', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('registration', sa.String(length=16), nullable=True))
    op.add_column('employees_totvs', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('employees_totvs', sa.Column('registration', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees_totvs', 'registration')
    op.drop_column('employees_totvs', 'admission_date')
    op.drop_column('employees', 'registration')
    op.drop_column('employees', 'admission_date')
    op.drop_table('educational_totvs')
    # ### end Alembic commands ###
