"""adjust column name group

Revision ID: 0cadeeb82018
Revises: 3367b63d0751
Create Date: 2023-12-13 21:21:40.884936

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0cadeeb82018'
down_revision: Union[str, None] = '3367b63d0751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_2', 'user', 'group', ['role_id'], ['id'])
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###
