"""adjust asset totvs model 4

Revision ID: 2573db876403
Revises: e2b4b8c83ac0
Create Date: 2023-12-05 22:26:08.260149

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2573db876403'
down_revision: Union[str, None] = 'e2b4b8c83ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_totvs', 'observations',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
