"""adjust status employee

Revision ID: d1652bdd9971
Revises: fe5977c54d5a
Create Date: 2023-12-13 21:37:35.109965

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1652bdd9971'
down_revision: Union[str, None] = 'fe5977c54d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('status', table_name='employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('status', 'employees', ['status'], unique=False)
    op.alter_column('employees', 'status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
