"""change code totvs models to string

Revision ID: 6a7ca06decc7
Revises: 6a5b8f9719d9
Create Date: 2023-12-06 20:14:18.430361

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a7ca06decc7'
down_revision: Union[str, None] = '6a5b8f9719d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_types_totvs', 'code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('assets_totvs', 'code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('employees_totvs', 'code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees_totvs', 'code',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('assets_totvs', 'code',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('asset_types_totvs', 'code',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
