"""add id to pivot tables

Revision ID: 3367b63d0751
Revises: 8531957a9853
Create Date: 2023-12-13 21:19:51.434810

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3367b63d0751'
down_revision: Union[str, None] = '8531957a9853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_permissions', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('invoice_assets', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('lending_witnesses', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lending_witnesses', 'id')
    op.drop_column('invoice_assets', 'id')
    op.drop_column('group_permissions', 'id')
    # ### end Alembic commands ###
