"""adjust unique code totvs

Revision ID: cc92ac71b072
Revises: 3fe3538f53b6
Create Date: 2023-12-13 21:57:53.171778

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc92ac71b072'
down_revision: Union[str, None] = '3fe3538f53b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'asset', ['code'])
    op.create_unique_constraint(None, 'asset_type', ['code'])
    op.create_unique_constraint(None, 'asset_types_totvs', ['code'])
    op.create_unique_constraint(None, 'cost_center', ['code'])
    op.create_unique_constraint(None, 'cost_centers_totvs', ['code'])
    op.create_unique_constraint(None, 'employee_roles', ['code'])
    op.create_unique_constraint(None, 'genders', ['code'])
    op.create_unique_constraint(None, 'genders_totvs', ['code'])
    op.create_unique_constraint(None, 'marital_status', ['code'])
    op.create_unique_constraint(None, 'marital_status_totvs', ['code'])
    op.create_unique_constraint(None, 'nationalities', ['code'])
    op.create_unique_constraint(None, 'nationalities_totvs', ['code'])
    op.create_unique_constraint(None, 'roles_totvs', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_totvs', type_='unique')
    op.drop_constraint(None, 'nationalities_totvs', type_='unique')
    op.drop_constraint(None, 'nationalities', type_='unique')
    op.drop_constraint(None, 'marital_status_totvs', type_='unique')
    op.drop_constraint(None, 'marital_status', type_='unique')
    op.drop_constraint(None, 'genders_totvs', type_='unique')
    op.drop_constraint(None, 'genders', type_='unique')
    op.drop_constraint(None, 'employee_roles', type_='unique')
    op.drop_constraint(None, 'cost_centers_totvs', type_='unique')
    op.drop_constraint(None, 'cost_center', type_='unique')
    op.drop_constraint(None, 'asset_types_totvs', type_='unique')
    op.drop_constraint(None, 'asset_type', type_='unique')
    op.drop_constraint(None, 'asset', type_='unique')
    # ### end Alembic commands ###
