"""adjust employee model

Revision ID: cbcb2732703c
Revises: cc92ac71b072
Create Date: 2023-12-15 22:31:16.894399

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbcb2732703c'
down_revision: Union[str, None] = 'cc92ac71b072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'nationality_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'marital_status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'marital_status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'nationality_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
