"""add update invoice pivot table

Revision ID: 163f8f3b15d7
Revises: 2cb5c6d51948
Create Date: 2024-01-16 22:27:19.196531

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "163f8f3b15d7"
down_revision: Union[str, None] = "2cb5c6d51948"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice_assets", sa.Column("quantity", sa.Float(), nullable=False))
    op.add_column(
        "invoice_assets", sa.Column("unit_value", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice_assets", "unit_value")
    op.drop_column("invoice_assets", "quantity")
    # ### end Alembic commands ###
