"""add lending status

Revision ID: 6fc4512cfa04
Revises: 543fb8bec7ab
Create Date: 2024-02-05 22:21:06.397892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fc4512cfa04"
down_revision: Union[str, None] = "543fb8bec7ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lending_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("lending", sa.Column("status_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "lending", "lending_status", ["status_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lending", type_="foreignkey")
    op.drop_column("lending", "status_id")
    op.drop_table("lending_status")
    # ### end Alembic commands ###
