"""add chip to term

Revision ID: 1a262007e6fa
Revises: 872467a523f5
Create Date: 2024-04-19 15:32:55.499185

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a262007e6fa"
down_revision: Union[str, None] = "872467a523f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "term_item", sa.Column("line_number", sa.String(length=15), nullable=True)
    )
    op.add_column(
        "term_item", sa.Column("operator", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term_item", "operator")
    op.drop_column("term_item", "line_number")
    # ### end Alembic commands ###
