"""remove glpi term

Revision ID: a864fda63408
Revises: c08e63df8653
Create Date: 2024-03-05 19:34:40.142260

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a864fda63408"
down_revision: Union[str, None] = "c08e63df8653"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term", "glpi_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "term", sa.Column("glpi_number", mysql.VARCHAR(length=25), nullable=True)
    )
    # ### end Alembic commands ###
