"""update verification category

Revision ID: d1e87ef23648
Revises: daf79536589f
Create Date: 2024-01-19 22:21:38.320902

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1e87ef23648"
down_revision: Union[str, None] = "daf79536589f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("verification", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "verification", "verification_category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verification", type_="foreignkey")
    op.drop_column("verification", "category_id")
    op.drop_table("verification_category")
    # ### end Alembic commands ###
