"""add lending revoke signed date

Revision ID: 4488332eb1b8
Revises: 6fc4512cfa04
Create Date: 2024-02-06 21:48:32.472718

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4488332eb1b8"
down_revision: Union[str, None] = "6fc4512cfa04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lending", sa.Column("revoke_signed_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lending", "revoke_signed_date")
    # ### end Alembic commands ###
