"""update invoice model

Revision ID: d8ca5084060b
Revises: 8ac59d352222
Create Date: 2024-01-17 20:06:03.344565

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8ca5084060b"
down_revision: Union[str, None] = "8ac59d352222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices", "file_name", existing_type=mysql.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices", "file_name", existing_type=mysql.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
