"""adjust invoice asset relationship

Revision ID: a53fdc401648
Revises: 01e63dba3814
Create Date: 2024-02-13 22:28:44.492036

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a53fdc401648"
down_revision: Union[str, None] = "01e63dba3814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset", sa.Column("invoice_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "asset", "invoices", ["invoice_id"], ["id"])
    op.drop_constraint("invoices_ibfk_1", "invoices", type_="foreignkey")
    op.drop_column("invoices", "asset_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("asset_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key("invoices_ibfk_1", "invoices", "asset", ["asset_id"], ["id"])
    op.drop_constraint(None, "asset", type_="foreignkey")
    op.drop_column("asset", "invoice_id")
    # ### end Alembic commands ###
