"""add job position

Revision ID: cbc6cdab6542
Revises: 6ab5492b3699
Create Date: 2024-08-30 11:26:00.814875

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbc6cdab6542'
down_revision: Union[str, None] = '6ab5492b3699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_disposal_reason',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('asset_disposal', sa.Column('reason_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'asset_disposal', 'asset_disposal_reason', ['reason_id'], ['id'])
    op.drop_column('asset_disposal', 'reason')
    op.add_column('employees', sa.Column('job_position', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'job_position')
    op.add_column('asset_disposal', sa.Column('reason', mysql.VARCHAR(length=15), nullable=False))
    op.drop_constraint(None, 'asset_disposal', type_='foreignkey')
    op.drop_column('asset_disposal', 'reason_id')
    op.drop_table('asset_disposal_reason')
    # ### end Alembic commands ###
