"""remove discard reason from asset

Revision ID: 6ab5492b3699
Revises: 3692d64da30b
Create Date: 2024-08-21 10:17:06.793313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ab5492b3699"
down_revision: Union[str, None] = "3692d64da30b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset", "discard_reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset", sa.Column("discard_reason", mysql.VARCHAR(length=255), nullable=True)
    )
    # ### end Alembic commands ###
