"""adjusts

Revision ID: 22c4fa2d819f
Revises: 26e2f8d64255
Create Date: 2024-02-20 22:08:40.860052

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22c4fa2d819f"
down_revision: Union[str, None] = "26e2f8d64255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upgrade_attachment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upgrade_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("file_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["upgrade_id"],
            ["upgrade.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("lending_witnesses")
    op.add_column(
        "employees", sa.Column("employer_end_contract_date", sa.Date(), nullable=True)
    )
    op.add_column("maintenance", sa.Column("open_date_glpi", sa.Date(), nullable=True))
    op.add_column(
        "maintenance", sa.Column("open_date_supplier", sa.Date(), nullable=True)
    )
    op.add_column(
        "maintenance",
        sa.Column("incident_description", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "upgrade", sa.Column("invoice_number", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upgrade", "invoice_number")
    op.drop_column("maintenance", "incident_description")
    op.drop_column("maintenance", "open_date_supplier")
    op.drop_column("maintenance", "open_date_glpi")
    op.drop_column("employees", "employer_end_contract_date")
    op.create_table(
        "lending_witnesses",
        sa.Column("lending_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("witness_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["lending_id"], ["lending.id"], name="lending_witnesses_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["witness_id"], ["witness.id"], name="lending_witnesses_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("lending_id", "witness_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("upgrade_attachment")
    # ### end Alembic commands ###
