"""refactore term

Revision ID: c08e63df8653
Revises: 47d83a332341
Create Date: 2024-03-01 21:40:06.776635

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c08e63df8653"
down_revision: Union[str, None] = "47d83a332341"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "term_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("size", sa.String(length=3), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "term_item_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "term_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "term",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("document_revoke_id", sa.Integer(), nullable=True),
        sa.Column("workload_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("cost_center_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("term_item_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=30), nullable=True),
        sa.Column("manager", sa.String(length=50), nullable=True),
        sa.Column("business_executive", sa.String(length=50), nullable=True),
        sa.Column("project", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("observations", sa.String(length=255), nullable=True),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("revoke_signed_date", sa.Date(), nullable=True),
        sa.Column("glpi_number", sa.String(length=25), nullable=True),
        sa.ForeignKeyConstraint(
            ["cost_center_id"],
            ["cost_centers_totvs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_revoke_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["term_status.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_item_id"],
            ["term_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["term_item_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workload_id"],
            ["workload.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("term")
    op.drop_table("term_status")
    op.drop_table("term_item_type")
    op.drop_table("term_item")
    # ### end Alembic commands ###
