"""update asset tovs observations

Revision ID: 8ac59d352222
Revises: 76bae55a48a6
Create Date: 2024-01-17 16:28:15.842710

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ac59d352222"
down_revision: Union[str, None] = "76bae55a48a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets_totvs",
        "observations",
        existing_type=mysql.VARCHAR(length=600),
        type_=sa.String(length=999),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets_totvs",
        "observations",
        existing_type=sa.String(length=999),
        type_=mysql.VARCHAR(length=600),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
