"""add lending type

Revision ID: 0cc0cb42c691
Revises: 1ee8af3e3125
Create Date: 2024-01-23 21:18:53.912546

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc0cb42c691"
down_revision: Union[str, None] = "1ee8af3e3125"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lending_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "lending",
        sa.Column(
            "type_id", sa.Integer(), sa.ForeignKey("lending_type.id"), nullable=False
        ),
    )
    op.create_foreign_key(None, "lending", "lending_type", ["type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lending", type_="foreignkey")
    op.drop_column("lending", "type_id")
    op.drop_table("lending_type")
    # ### end Alembic commands ###
