"""adjust create lending term

Revision ID: f9141298d7e2
Revises: da8e37c52654
Create Date: 2024-02-13 17:17:21.395428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9141298d7e2"
down_revision: Union[str, None] = "da8e37c52654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lending", "workload_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lending", "workload_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
