"""adjust invoice asset

Revision ID: cd2f3960dc94
Revises: 5df3e57ba4fa
Create Date: 2024-01-21 19:11:07.916620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd2f3960dc94"
down_revision: Union[str, None] = "5df3e57ba4fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoice_assets")  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_assets",
        sa.Column("invoice_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("asset_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("unit_value", mysql.FLOAT(), nullable=False),
        sa.Column("id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["asset.id"], name="invoice_assets_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name="invoice_assets_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("invoice_id", "asset_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
