"""update asset observations

Revision ID: 76bae55a48a6
Revises: 163f8f3b15d7
Create Date: 2024-01-17 16:13:48.119283

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76bae55a48a6"
down_revision: Union[str, None] = "163f8f3b15d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "asset",
        "observations",
        existing_type=mysql.VARCHAR(length=500),
        type_=sa.String(length=999),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "asset",
        "observations",
        existing_type=sa.String(length=999),
        type_=mysql.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
