"""add revoke doc lending model

Revision ID: da8e37c52654
Revises: 866160a89cb0
Create Date: 2024-02-13 15:38:01.757824

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da8e37c52654"
down_revision: Union[str, None] = "866160a89cb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lending", sa.Column("document_revoke_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "lending", "document", ["document_revoke_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lending", type_="foreignkey")
    op.drop_column("lending", "document_revoke_id")
    # ### end Alembic commands ###
