"""add asset disposal

Revision ID: 3692d64da30b
Revises: 6e60998b1d18
Create Date: 2024-08-21 09:40:32.863453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3692d64da30b"
down_revision: Union[str, None] = "6e60998b1d18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_disposal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("write_off_date", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=15), nullable=False),
        sa.Column("justification", sa.String(length=255), nullable=True),
        sa.Column("observations", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_disposal_attachment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("disposal_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["disposal_id"],
            ["asset_disposal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset_disposal_attachment")
    op.drop_table("asset_disposal")
    # ### end Alembic commands ###
