"""add asset to maintenance

Revision ID: fb9ccc3a07d3
Revises: a53fdc401648
Create Date: 2024-02-14 20:10:06.212966

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb9ccc3a07d3"
down_revision: Union[str, None] = "a53fdc401648"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maintenance", sa.Column("asset_id", sa.Integer(), nullable=False))
    op.add_column("maintenance", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "maintenance", "employees", ["employee_id"], ["id"])
    op.create_foreign_key(None, "maintenance", "asset", ["asset_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "maintenance", type_="foreignkey")
    op.drop_constraint(None, "maintenance", type_="foreignkey")
    op.drop_column("maintenance", "employee_id")
    op.drop_column("maintenance", "asset_id")
    # ### end Alembic commands ###
