"""add manager and department

Revision ID: 543fb8bec7ab
Revises: b872fdd293a4
Create Date: 2024-02-05 20:47:51.639037

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "543fb8bec7ab"
down_revision: Union[str, None] = "b872fdd293a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("department", sa.String(length=255), nullable=False)
    )
    op.add_column("user", sa.Column("manager", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "manager")
    op.drop_column("user", "department")
    # ### end Alembic commands ###
