"""adjusts

Revision ID: 40da88cf4fbe
Revises: 3b292c434f06
Create Date: 2024-02-28 19:37:41.868588

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40da88cf4fbe'
down_revision: Union[str, None] = '3b292c434f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade', sa.Column('value', sa.Float(), nullable=True))
    op.drop_column('upgrade', 'glpi_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade', sa.Column('glpi_number', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('upgrade', 'value')
    # ### end Alembic commands ###
