"""adjust witnesess model

Revision ID: 866160a89cb0
Revises: 16b0954a48e4
Create Date: 2024-02-13 12:34:10.599806

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "866160a89cb0"
down_revision: Union[str, None] = "16b0954a48e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "witness", "lending_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "witness", "lending_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
