"""add educational level

Revision ID: 2cb5c6d51948
Revises: 05ad561b3546
Create Date: 2024-01-12 14:19:01.076089

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cb5c6d51948'
down_revision: Union[str, None] = '05ad561b3546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('educational_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'educational_totvs', ['educational_level_id'], ['id'])
    op.add_column('employees_totvs', sa.Column('education_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees_totvs', 'education_level')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'educational_level_id')
    # ### end Alembic commands ###
