"""add bu

Revision ID: 3b292c434f06
Revises: 22c4fa2d819f
Create Date: 2024-02-24 15:50:16.307199

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b292c434f06'
down_revision: Union[str, None] = '22c4fa2d819f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lending', sa.Column('bu', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lending', 'bu')
    # ### end Alembic commands ###
