"""adjust upgrade maintenance

Revision ID: 26e2f8d64255
Revises: fb9ccc3a07d3
Create Date: 2024-02-14 22:55:45.252340

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26e2f8d64255"
down_revision: Union[str, None] = "fb9ccc3a07d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("upgrade", sa.Column("asset_id", sa.Integer(), nullable=False))
    op.add_column("upgrade", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "upgrade", "asset", ["asset_id"], ["id"])
    op.create_foreign_key(None, "upgrade", "employees", ["employee_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "upgrade", type_="foreignkey")
    op.drop_constraint(None, "upgrade", type_="foreignkey")
    op.drop_column("upgrade", "employee_id")
    op.drop_column("upgrade", "asset_id")
    # ### end Alembic commands ###
