"""add timestamp upgrade model

Revision ID: 3ae6d345fc44
Revises: 01b0eafaaf2d
Create Date: 2024-04-30 20:35:54.129794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ae6d345fc44"
down_revision: Union[str, None] = "01b0eafaaf2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upgrade",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "upgrade",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upgrade", "updated_at")
    op.drop_column("upgrade", "created_at")
    # ### end Alembic commands ###
