"""add delete term

Revision ID: 6e60998b1d18
Revises: fd119aa12f3e
Create Date: 2024-07-09 17:43:05.844240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e60998b1d18"
down_revision: Union[str, None] = "fd119aa12f3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("term", sa.Column("deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term", "deleted")
    # ### end Alembic commands ###
