"""add criticality maintenance

Revision ID: 872467a523f5
Revises: 26891681233c
Create Date: 2024-04-12 15:43:07.615918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "872467a523f5"
down_revision: Union[str, None] = "26891681233c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "maintenance", sa.Column("criticality_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "maintenance", "maintenance_criticality", ["criticality_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "maintenance", type_="foreignkey")
    op.drop_column("maintenance", "criticality_id")
    # ### end Alembic commands ###
