"""update invoice assets table pivot

Revision ID: daf79536589f
Revises: d8ca5084060b
Create Date: 2024-01-17 21:27:40.441896

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daf79536589f"
down_revision: Union[str, None] = "d8ca5084060b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice_assets",
        "quantity",
        existing_type=mysql.FLOAT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_assets",
        "unit_value",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice_assets",
        "unit_value",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "invoice_assets",
        "quantity",
        existing_type=sa.Integer(),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
