"""add adjust lending

Revision ID: b872fdd293a4
Revises: 0cc0cb42c691
Create Date: 2024-02-03 19:58:12.554264

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b872fdd293a4"
down_revision: Union[str, None] = "0cc0cb42c691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lending", sa.Column("business_executive", sa.String(length=50), nullable=True)
    )
    op.add_column("lending", sa.Column("goal", sa.String(length=255), nullable=True))
    op.add_column("lending", sa.Column("project", sa.String(length=100), nullable=True))
    op.add_column(
        "lending", sa.Column("location", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lending", "location")
    op.drop_column("lending", "project")
    op.drop_column("lending", "goal")
    op.drop_column("lending", "business_executive")
    # ### end Alembic commands ###
