"""add ms office to lending

Revision ID: 73d90a21e70d
Revises: e7f910d608b6
Create Date: 2024-04-06 12:50:16.974524

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d90a21e70d"
down_revision: Union[str, None] = "e7f910d608b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lending", sa.Column("ms_office", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lending", "ms_office")
    # ### end Alembic commands ###
