"""adjust create invoice

Revision ID: 01e63dba3814
Revises: f9141298d7e2
Create Date: 2024-02-13 22:24:34.492528

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01e63dba3814"
down_revision: Union[str, None] = "f9141298d7e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices", "asset_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices", "asset_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
