"""add manager inventory

Revision ID: fdd4419118a9
Revises: efe3a8c3093b
Create Date: 2025-10-14 10:27:22.570074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdd4419118a9"
down_revision: Union[str, None] = "efe3a8c3093b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory", sa.Column("manager", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory", "manager")
    # ### end Alembic commands ###
