"""Adjust inventory phone

Revision ID: e693fb61e43d
Revises: d6e10a2abf45
Create Date: 2025-01-16 17:38:10.016477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e693fb61e43d"
down_revision: Union[str, None] = "d6e10a2abf45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory",
        "phone",
        existing_type=mysql.VARCHAR(length=11),
        type_=sa.String(length=16),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory",
        "phone",
        existing_type=sa.String(length=16),
        type_=mysql.VARCHAR(length=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
