"""adjust model term

Revision ID: 22035165c296
Revises: 14c94da41df3
Create Date: 2025-07-11 22:33:57.706408

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22035165c296"
down_revision: Union[str, None] = "14c94da41df3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "term", sa.Column("signer_email", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "term",
        sa.Column("principal_email_signer", sa.String(length=100), nullable=True),
    )

    # Preencher as colunas com dados existentes
    connection = op.get_bind()

    # Atualizar signer_email na tabela term com o email do employee vinculado
    connection.execute(
        sa.text(
            """
        UPDATE term
        SET signer_email = (
            SELECT employee.email
            FROM employee
            WHERE employee.id = term.employee_id
        )
        WHERE term.employee_id IS NOT NULL
    """
        )
    )

    # Atualizar principal_email_signer na tabela term
    connection.execute(
        sa.text(
            """
        UPDATE term
        SET principal_email_signer = 'beatriz.cunha@solutis.com.br'
    """
        )
    )

    # Atualizar signer_email na tabela lending com o email do employee vinculado
    connection.execute(
        sa.text(
            """
        UPDATE lending
        SET signer_email = (
            SELECT employee.email
            FROM employee
            WHERE employee.id = lending.employee_id
        )
        WHERE lending.employee_id IS NOT NULL
    """
        )
    )

    # Atualizar principal_email_signer na tabela lending
    connection.execute(
        sa.text(
            """
        UPDATE lending
        SET principal_email_signer = 'beatriz.cunha@solutis.com.br'
    """
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term", "principal_email_signer")
    op.drop_column("term", "signer_email")
    # ### end Alembic commands ###
