"""add click sign ids

Revision ID: be46795e6569
Revises: d6055983828c
Create Date: 2025-04-18 23:02:48.739808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "be46795e6569"
down_revision: Union[str, None] = "d6055983828c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("sign_doc_id", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "document", sa.Column("sign_envelope_id", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_document_sign_doc_id"), "document", ["sign_doc_id"], unique=True
    )
    op.create_index(
        op.f("ix_document_sign_envelope_id"),
        "document",
        ["sign_envelope_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_sign_envelope_id"), table_name="document")
    op.drop_index(op.f("ix_document_sign_doc_id"), table_name="document")
    op.drop_column("document", "sign_envelope_id")
    op.drop_column("document", "sign_doc_id")
    # ### end Alembic commands ###
