"""recreate document clicksign

Revision ID: 14c94da41df3
Revises: be46795e6569
Create Date: 2025-07-11 20:42:04.955563

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14c94da41df3"
down_revision: Union[str, None] = "be46795e6569"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lending", sa.Column("signer_email", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "lending",
        sa.Column("principal_email_signer", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lending", "principal_email_signer")
    op.drop_column("lending", "signer_email")
    # ### end Alembic commands ###
