"""adjust model term

Revision ID: 22035165c296
Revises: 14c94da41df3
Create Date: 2025-07-11 22:33:57.706408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "22035165c296"
down_revision: Union[str, None] = "14c94da41df3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "term", sa.Column("signer_email", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "term",
        sa.Column("principal_email_signer", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("term", "principal_email_signer")
    op.drop_column("term", "signer_email")
    # ### end Alembic commands ###
