"""Adjust inventory

Revision ID: d6e10a2abf45
Revises: 8259cbcc566c
Create Date: 2025-01-10 21:43:38.284008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6e10a2abf45"
down_revision: Union[str, None] = "8259cbcc566c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory_extra_item")
    op.add_column(
        "inventory", sa.Column("extra_items", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory", "extra_items")
    op.create_table(
        "inventory_extra_item",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=True),
        sa.Column("inventory_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"], ["inventory.id"], name="inventory_extra_item_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
