# Generated by Django 3.2 on 2023-06-30 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.images
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('path', models.FileField(upload_to='')),
                ('signed', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaterialDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_material_docs', to='lending.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, storage=utils.images.OverwriteImage(), upload_to=utils.images.upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('signed', models.DateField(null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witnesses', to='lending.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialVerificationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=150)),
                ('material_verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_verification_answers', to='lending.materialverification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialHistorical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('Locação', 'Locação'), ('Manutenção', 'Manutenção'), ('Descarte', 'Descarte'), ('Melhorias', 'Melhorias')], max_length=13)),
                ('occurance', models.DateField(auto_now_add=True)),
                ('observations', models.CharField(default='', max_length=150)),
                ('employee_material_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_historicals', to='lending.employeematerialdoc')),
                ('materail_verification_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_historicals', to='lending.materialverificationanswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('Reservado', 'Reservado'), ('Disponível', 'Disponível'), ('Em manutenção', 'Em manutenção')], default='Disponível', max_length=13)),
                ('observation', models.CharField(default='', max_length=150)),
                ('assurance', models.DateField(null=True)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='lending.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeematerialdoc',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_material_docs', to='lending.material'),
        ),
    ]
