# Generated by Django 3.2 on 2023-07-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeematerialdoc',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_material_doc', to='lending.document'),
        ),
    ]
